// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSW1_s4aI-5bFgctl8v6n_NnCU1CsyREY',
    appId: '1:1019719663138:web:5fa622304d3bafd627147b',
    messagingSenderId: '1019719663138',
    projectId: 'cowcardfile-b31b6',
    authDomain: 'cowcardfile-b31b6.firebaseapp.com',
    storageBucket: 'cowcardfile-b31b6.appspot.com',
    measurementId: 'G-8E34X9DLRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBByfiOIpbYCRjP8Sjk6YKZbfWgYNC8hvI',
    appId: '1:1019719663138:android:f793a3f8fb0fab9727147b',
    messagingSenderId: '1019719663138',
    projectId: 'cowcardfile-b31b6',
    storageBucket: 'cowcardfile-b31b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCODy_3-qhJxVHkyop6pShKXwD595WlBVc',
    appId: '1:1019719663138:ios:0fe44454aa2c78a927147b',
    messagingSenderId: '1019719663138',
    projectId: 'cowcardfile-b31b6',
    storageBucket: 'cowcardfile-b31b6.appspot.com',
    iosClientId: '1019719663138-7b33brh2rrf1o6t20dadjudcuecn5f5m.apps.googleusercontent.com',
    iosBundleId: 'com.mhbravco.cowcardfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCODy_3-qhJxVHkyop6pShKXwD595WlBVc',
    appId: '1:1019719663138:ios:0fe44454aa2c78a927147b',
    messagingSenderId: '1019719663138',
    projectId: 'cowcardfile-b31b6',
    storageBucket: 'cowcardfile-b31b6.appspot.com',
    iosClientId: '1019719663138-7b33brh2rrf1o6t20dadjudcuecn5f5m.apps.googleusercontent.com',
    iosBundleId: 'com.mhbravco.cowcardfile',
  );
}
